# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: showtime.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'showtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\"+\n\x0bScheduleDay\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"#\n\x13MoviesByDateRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\":\n\x14MoviesByDateResponse\x12\"\n\x0cschedule_day\x18\x01 \x01(\x0b\x32\x0c.ScheduleDay\"2\n\x10ScheduleResponse\x12\x1e\n\x08schedule\x18\x01 \x03(\x0b\x32\x0c.ScheduleDay\"\x07\n\x05\x45mpty2x\n\x08Showtime\x12*\n\x0bGetSchedule\x12\x06.Empty\x1a\x11.ScheduleResponse\"\x00\x12@\n\x0fGetMoviesByDate\x12\x14.MoviesByDateRequest\x1a\x15.MoviesByDateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'showtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULEDAY']._serialized_start=18
  _globals['_SCHEDULEDAY']._serialized_end=61
  _globals['_MOVIESBYDATEREQUEST']._serialized_start=63
  _globals['_MOVIESBYDATEREQUEST']._serialized_end=98
  _globals['_MOVIESBYDATERESPONSE']._serialized_start=100
  _globals['_MOVIESBYDATERESPONSE']._serialized_end=158
  _globals['_SCHEDULERESPONSE']._serialized_start=160
  _globals['_SCHEDULERESPONSE']._serialized_end=210
  _globals['_EMPTY']._serialized_start=212
  _globals['_EMPTY']._serialized_end=219
  _globals['_SHOWTIME']._serialized_start=221
  _globals['_SHOWTIME']._serialized_end=341
# @@protoc_insertion_point(module_scope)
